from PyQt5 import QtCore, QtGui, QtWidgets
import sqlite3

from PyQt5.QtWidgets import QMessageBox
class ViewPatientsAdmin( object ):
    def ClearData(self):
        self.FullName.clear()
        self.EditFullName.clear()
        self.EditBirthDate.clear()
        self.EditAddress.clear()
        self.EditPhone.clear()
        self.EditStatus.setCurrentText( "" )
        self.EditGender.setCurrentText( "" )
        self.EditIllness.clear()
        self.EditEmail.clear()
    # Function to load data
    def loadingData(self):
        db = sqlite3.connect( "project.db" )
        result = db.execute( "select * from PatientInformation" )
        self.tableWidget.setRowCount( 0 )
        # Using two for loops to insert the data from result query to tablewidgets
        for RowNum, RowDATA in enumerate( result ):
            self.tableWidget.insertRow( RowNum )
            for ColumnNum, ColumnData in enumerate( RowDATA ):
                self.tableWidget.setItem( RowNum, ColumnNum, QtWidgets.QTableWidgetItem( str( ColumnData ) ) )
        db.close()
        # Clearing all the fields
        self.ClearData()
    # Function to search for Patients
    def SearchClicked(self):
        # Get the data from the user
        Name = self.FullName.text()
        db = sqlite3.connect("project.db")
        result = db.execute("select * from PatientInformation where name="+ "'"+Name+"'")
        self.tableWidget.setRowCount( 0 )
        # Using two for loops to insert the data into tableWidgets
        for RowNum, RowDATA in enumerate( result ):
            self.tableWidget.insertRow( RowNum )
            for ColumnNum, ColumnData in enumerate( RowDATA ):
                self.tableWidget.setItem( RowNum, ColumnNum, QtWidgets.QTableWidgetItem( str( ColumnData ) ) )
        list = [] # List to append data from ViewName query to use the data for setting lineEdits
        ########################
        ViewName = db.execute("select * from PatientInformation where name="+ "'"+Name+"'")
        for RowNum, RowDATA in enumerate( ViewName ):
            for ColumnNum, ColumnData in enumerate( RowDATA ):
                list.append(ColumnData)
        self.EditFullName.setText(list[0])
        self.EditBirthDate.setText(list[1])
        self.EditAddress.setText(list[2])
        self.EditPhone.setText(str(list[3]))
        self.EditStatus.setCurrentText(list[4])
        self.EditGender.setCurrentText(list[5])
        self.EditIllness.setText(list[6])
        self.EditEmail.setText(list[7])

        db.close()
    # Function to Delete Patients based on Name of Patient
    def DeleteClicked(self):
        # Get Name from the user to delete the info
        Name = self.FullName.text()
        db = sqlite3.connect( "project.db" )
        db.execute( "delete from PatientInformation where name=" + "'" + Name + "'" ) # Query to delete info based on Name
        db.commit()
        message1 = QMessageBox()
        message1.setWindowTitle( "Successfull" )
        message1.setInformativeText( "You have successfully deleted information of :  " + Name )
        message1.exec_()
        result = db.execute("select * from PatientInformation")
        self.tableWidget.setRowCount( 0 )
        # Using two for loops to insert the data after deleting
        for RowNum, RowDATA in enumerate( result ):
            self.tableWidget.insertRow( RowNum )
            for ColumnNum, ColumnData in enumerate( RowDATA ):
                self.tableWidget.setItem( RowNum, ColumnNum, QtWidgets.QTableWidgetItem( str( ColumnData ) ) )

        db.close()
        # Clearing all the fields
        self.ClearData()
    # Function to Update Data from the Patients table
    def UpdateData(self):
        # Get the info from the user
        FullName = self.EditFullName.text()
        BirthDate = self.EditBirthDate.text()
        Address= self.EditAddress.text()
        Phone = self.EditPhone.text()
        Status = self.EditStatus.currentText()
        Gender = self.EditGender.currentText()
        Illness = self.EditIllness.text()
        Email = self.EditEmail.text()
        db = sqlite3.connect("project.db")
        # Update information of Patients based on Full Name
        db.execute("update PatientInformation set name=?, birthday=?, address=?, phone=?,status=?,gender=?, illness=?, email=? where name ="+"'"+FullName+"'",
                   (FullName, BirthDate, Address, Phone, Status, Gender, Illness, Email))
        db.commit()
        message1 = QMessageBox()
        message1.setWindowTitle( "Successfull" )
        message1.setInformativeText( "You have successfully updated information of :  " + FullName )
        message1.exec_()
        # Select data from the PatientInformation table to appear in tableWidgets after updating the data
        result = db.execute( "select * from PatientInformation where name=" + "'" + FullName + "'" )
        self.tableWidget.setRowCount( 0 )
        # Using two for loops to insert the data from result query into tableWidget
        for RowNum, RowDATA in enumerate( result ):
            self.tableWidget.insertRow( RowNum )
            for ColumnNum, ColumnData in enumerate( RowDATA ):
                self.tableWidget.setItem( RowNum, ColumnNum, QtWidgets.QTableWidgetItem( str( ColumnData ) ) )
        db.close()

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindowAdmin")
        MainWindow.resize(652, 561)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.SearchButton = QtWidgets.QPushButton(self.centralwidget)
        self.SearchButton.setGeometry(QtCore.QRect(260, 20, 91, 31))
        self.SearchButton.setObjectName("SearchB")
        self.SearchButton.clicked.connect(self.SearchClicked)
        self.ViewPatients = QtWidgets.QPushButton(self.centralwidget)
        self.ViewPatients.setGeometry(QtCore.QRect(534, 20, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.ViewPatients.setFont(font)
        self.ViewPatients.setObjectName("ViewBills")
        self.ViewPatients.clicked.connect( self.loadingData )
        self.UpdateButton = QtWidgets.QPushButton(self.centralwidget)
        self.UpdateButton.setGeometry(QtCore.QRect(520, 444, 91, 31))
        self.UpdateButton.setObjectName("UpdateRecordB")
        self.UpdateButton.clicked.connect(self.UpdateData)
        self.FullName = QtWidgets.QLineEdit(self.centralwidget)
        self.FullName.setGeometry(QtCore.QRect(100, 20, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.FullName.setFont(font)
        self.FullName.setObjectName("FullName")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 16, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.DeleteButton = QtWidgets.QPushButton(self.centralwidget)
        self.DeleteButton.setGeometry(QtCore.QRect(370, 20, 91, 31))
        self.DeleteButton.setObjectName("DeleteRecordB")
        self.DeleteButton.clicked.connect(self.DeleteClicked)
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(0, 60, 651, 291))
        self.tableWidget.setStyleSheet("background-color: rgb(235, 235, 255);\n"
"\n"
"")
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(8)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(7, item)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(30, 370, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(9)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(240, 369, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(9)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(284, 409, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(9)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(294, 450, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(9)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(290, 494, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(9)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(50, 491, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(9)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(40, 450, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(9)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_1")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(20, 410, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(9)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_2")
        self.EditFullName = QtWidgets.QLineEdit(self.centralwidget)
        self.EditFullName.setGeometry(QtCore.QRect(99, 370, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.EditFullName.setFont(font)
        self.EditFullName.setObjectName("EditFullName")
        self.EditEmail = QtWidgets.QLineEdit(self.centralwidget)
        self.EditEmail.setGeometry(QtCore.QRect(350, 494, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.EditEmail.setFont(font)
        self.EditEmail.setObjectName("EditEmail")
        self.EditIllness = QtWidgets.QLineEdit(self.centralwidget)
        self.EditIllness.setGeometry(QtCore.QRect(350, 452, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.EditIllness.setFont(font)
        self.EditIllness.setObjectName("EditIllness")
        self.EditPhone = QtWidgets.QLineEdit(self.centralwidget)
        self.EditPhone.setGeometry(QtCore.QRect(100, 493, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.EditPhone.setFont(font)
        self.EditPhone.setObjectName("EditPhone")
        self.EditAddress = QtWidgets.QLineEdit(self.centralwidget)
        self.EditAddress.setGeometry(QtCore.QRect(99, 452, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.EditAddress.setFont(font)
        self.EditAddress.setObjectName("EditAddress")
        self.EditStatus = QtWidgets.QComboBox(self.centralwidget)
        self.EditStatus.setGeometry(QtCore.QRect(350, 370, 81, 31))
        self.EditStatus.setObjectName("EditStatus")
        self.EditStatus.addItem("")
        self.EditStatus.setItemText(0, "")
        self.EditStatus.addItem("")
        self.EditStatus.addItem("")
        self.EditStatus.addItem("")
        self.EditStatus.addItem("")
        self.EditGender = QtWidgets.QComboBox(self.centralwidget)
        self.EditGender.setGeometry(QtCore.QRect(350, 410, 81, 31))
        self.EditGender.setObjectName("EditGender")
        self.EditGender.addItem("")
        self.EditGender.setItemText(0, "")
        self.EditGender.addItem("")
        self.EditGender.addItem("")
        self.EditGender.addItem("")
        self.EditBirthDate = QtWidgets.QLineEdit(self.centralwidget)
        self.EditBirthDate.setGeometry(QtCore.QRect(99, 410, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.EditBirthDate.setFont(font)
        self.EditBirthDate.setObjectName("EditBirthDate")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindowAdmin", "MainWindowAdmin"))
        self.SearchButton.setText(_translate("MainWindowAdmin", "Search"))
        self.ViewPatients.setText(_translate("MainWindowAdmin", "View All Patients"))
        self.UpdateButton.setText(_translate("MainWindowAdmin", "Update"))
        self.label.setText(_translate("MainWindowAdmin", "Full Name:"))
        self.DeleteButton.setText(_translate("MainWindowAdmin", "Delete"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindowAdmin", "Full Name"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindowAdmin", "Birth Date"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindowAdmin", "Address"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindowAdmin", "Phone"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindowAdmin", "Martial Status"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("MainWindowAdmin", "Gender"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("MainWindowAdmin", "Illness"))
        item = self.tableWidget.horizontalHeaderItem(7)
        item.setText(_translate("MainWindowAdmin", "Email"))
        self.label_2.setText(_translate("MainWindowAdmin", "Full Name:"))
        self.label_3.setText(_translate("MainWindowAdmin", "Martial Status:"))
        self.label_4.setText(_translate("MainWindowAdmin", "Gender:"))
        self.label_5.setText(_translate("MainWindowAdmin", "Illness:"))
        self.label_6.setText(_translate("MainWindowAdmin", "Email:"))
        self.label_7.setText(_translate("MainWindowAdmin", "Phone: "))
        self.label_8.setText(_translate("MainWindowAdmin", "Address:"))
        self.label_9.setText(_translate("MainWindowAdmin", "Birth Date:"))
        self.EditStatus.setItemText(1, _translate("MainWindowAdmin", "Single"))
        self.EditStatus.setItemText(2, _translate("MainWindowAdmin", "Married"))
        self.EditStatus.setItemText(3, _translate("MainWindowAdmin", "Divorced"))
        self.EditStatus.setItemText(4, _translate("MainWindowAdmin", "Widowed"))
        self.EditGender.setItemText(1, _translate("MainWindowAdmin", "Male"))
        self.EditGender.setItemText(2, _translate("MainWindowAdmin", "Female"))
        self.EditGender.setItemText(3, _translate("MainWindowAdmin", "Other"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = ViewPatientsAdmin()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
